### ISSUE TITLE
doesn't run

### ISSUE THREAD

**Issue by ProfessorDragon** [CdcOnGitHub/h#1]
the program doesn't seem to work properly, python gives me this error so it can't run :((
```dart
Traceback (most recent call last):
  File "h.py", line 1, in <module>
    import time
ModuleNotFoundError: No module named 'time'
```

**Comment by Xytrizareal** [comment]
HUH?!?!?!?!? ISNT FUCKIN TIME INPORTED TO PY BY DEFAULT LMAO
