### ISSUE TITLE
Missing library

### ISSUE THREAD

**Issue by ghost** [CdcOnGitHub/h#2]
Instructions unclear, where can I install print?

`Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'print' is not defined`

**Comment by ghost** [comment]
HOW THE FUCK DO U MESS UP PRINT!??!

**Comment by ProfessorDragon** [comment]
this cdc guy must have no clue what hes doing

**Comment by cdc-sys** [comment]
how.... literally.... how????

**Comment by TechStudent10** [comment]
how did you screw up the python standard library 😭

**Comment by ghost** [comment]
I still need an answer
